### ISSUE TITLE
Allocate Like Changing Allocation Values

### ISSUE THREAD

**Issue by bjsimmons606** [zowe/explorer-mvs#32]
When allocating like a dataset we have noticed allocation values like the secondary track and first extents are different from original dataset in the new dataset .

**Comment by Colin-Stone** [comment]
These values are not available yet via Atlas but can certainly be considered for the backlog. Does zosmf provide anything?.

**Comment by bjsimmons606** [comment]
I'm not sure if zOSMF provides anything to help with this

**Comment by stevenhorsman** [comment]
Migrated to: https://github.com/zowe/data-sets/issues/29
