### ISSUE TITLE
Not Getting All Attributes Back from API Using GET

### ISSUE THREAD

**Issue by bjsimmons606** [zowe/explorer-mvs#33]
Not Getting All Attributes Back from API Using GET dsn/attributes, https://{url}/datasets/{dsn}/attributes, only receive the following values back for every dataset.
[
  {
    "name": "{dsnName}",
    "blksize": "80",
    "lrecl": "80",
    "recfm": "FB",
    "dsorg": "PO"
  }
]
Was trying to use this to work around the allocate like issue #32 but with out all the attributes I can't use this as a work around.

**Comment by Colin-Stone** [comment]
What attributes are required?.

**Comment by bjsimmons606** [comment]
"name": "string",
    "blksize": "string",
    "lrecl": "string",
    "recfm": "string",
    "dsorg": "string",
    "alcunit": "string",
    "primary": "string",
    "secondary": "string",
   The same that are required to create a dataset.
