### ISSUE TITLE
Data set listing fails for data set with DSORG=HFS

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/explorer-mvs#44]
With Zowe build 430:

The data set listing fails for * HLQ=IGY:

Status: 500
{"timestamp":"2019-01-21T21:07:44.999+0000","status":500,"error":"Internal Server Error","message":"Character: HFS was not a recognised data set organisation type","path":"/api/v1/datasets/IGY"}
In IGY data set listing, there is an HFS file system data set (IGY.V4R2M0.HFS), DSORG=HFS (Unsupported Data Type).

**Comment by stevenhorsman** [comment]
This isn't a valid parameter as listed in the swagger catalog
