### ISSUE TITLE
Data set listing fails with error message "No enum constant org.zowe.data.sets.model.AllocationUnitType.BYTE"

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/explorer-mvs#46]
With Zowe build 430:

The data set listing fails for * HLQ=USER: 

Status: 500
{"timestamp":"2019-01-21T21:56:33.112+0000","status":500,"error":"Internal Server Error","message":"No enum constant org.zowe.data.sets.model.AllocationUnitType.BYTE","path":"/api/v1/datasets/USER"}

**Comment by stevenhorsman** [comment]
This isn't a valid parameter as listed in the swagger catalog
